apiVersion: apps/v1
kind: Deployment
metadata:
  name: FLy-Far-Ladies-Apiv2
spec:
  selector:
    matchLabels:
      app: FLy-Far-Ladies-Apiv2
  replicas: 2
  template:
    metadata:
      labels:
        app: FLy-Far-Ladies-Apiv2
    spec:
      containers:
        - name: FLy-Far-Ladies-Apiv2
          image: fahimffi/flyfarladiesapiv2
          ports:
            - containerPort: 3000